In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2

Задание 1 В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.2614646  0.97716307 0.23813724 ... 0.79021872 0.03358157 0.06156004]
 [0.14301029 0.70455167 0.26811102 ... 0.60137342 0.12927852 0.84210546]
 [0.70953313 0.77498021 0.91847246 ... 0.71663684 0.93230415 0.35229454]
 ...
 [0.7281985  0.87277767 0.43021637 ... 0.82956662 0.08309961 0.10447901]
 [0.503204   0.42348802 0.08352312 ... 0.29508087 0.83756942 0.80014803]
 [0.62749546 0.41582317 0.51664562 ... 0.68698969 0.57664418 0.65427339]]
[[0.68238129 0.48585343 0.25127875 ... 0.92442749 0.32352358 0.82934253]
 [0.49802693 0.54685844 0.53737814 ... 0.50758497 0.30770401 0.11836316]
 [0.35785074 0.43600746 0.38130542 ... 0.91393404 0.12138272 0.38483158]
 ...
 [0.4693422  0.07083859 0.84987581 ... 0.63702476 0.85483746 0.89833424]
 [0.7103238  0.11555992 0.64045878 ... 0.92731495 0.10197366 0.49677239]
 [0.82198341 0.29636129 0.95582697 ... 0.2246075  0.61149937 0.10447726]]


Без использования numpy

In [31]:
a = [[1, 2], [3, 4]]#для проверки
b = [[5, 6], [7, 8]]#для проверки

def mult(a, b):
    result = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

result = mult(a, b)
print(result)

[[19, 22], [43, 50]]


C использованием numpy

In [32]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

print(np_mult(a, b))

[[19 22]
 [43 50]]


In [12]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 20 µs, sys: 3 µs, total: 23 µs
Wall time: 26.7 µs


In [13]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 48 µs, sys: 7 µs, total: 55 µs
Wall time: 59.4 µs


In [14]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0

Задание 2 Вам подаются на вход два вектора a и b в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy и без. Засеките время работы, как это показано в заданиях выше.

In [15]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.01949659 0.43110525 0.23496334] [0.23143386 0.83891444 0.19827139]


In [16]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i]*b[i]
    return s

In [18]:
def np_scalar_product(a, b):
    s = np.dot(a, b)
    return s

In [19]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 25 µs, sys: 0 ns, total: 25 µs
Wall time: 30 µs
CPU times: user 126 µs, sys: 18 µs, total: 144 µs
Wall time: 663 µs


0.0

Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

Ответ: Методы NumPy оказываются эффективнее благодаря использованию массивов и векторизации операций.
Скорость вычислений в NumPy обычно очень высокая благодаря оптимизированным алгоритмам и использованию библиотек на языке C. Это позволяет NumPy эффективно обрабатывать большие объемы данных и выполнять сложные математические операции за короткое время.

Задание 3. Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести 0.

In [20]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diag(a)
  even_diag = diag[diag % 2 == 0]
  if len(even_diag) == 0:
    return 0
  else:
    return np.sum(even_diag)

In [21]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 4, 6, 3, 5],
       [9, 8, 5, 5, 1],
       [7, 9, 2, 7, 2],
       [8, 8, 2, 7, 3],
       [9, 7, 5, 6, 1]])

In [22]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 177 µs, sys: 0 ns, total: 177 µs
Wall time: 184 µs


10

Задание 4. На вход дан двумерный массив X . Напишите функцию, которая для каждой строчки x=(x1,x2,…,xn) массива X строит строчку s=(s1,s2,…,sn) , где sk=(x1+...+xk)/k , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и X .

In [28]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return np.mean(A**2)

In [24]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[8.98849516e-01 1.25604295e-01 8.34436410e-02 3.61974488e-01
 7.03924077e-01 2.60917746e-01 4.42593354e-01 7.60599367e-01
 6.31165594e-01 4.57862830e-02 3.85686153e-01 2.18847597e-01
 4.03016643e-01 1.70344163e-01 8.25414539e-01 5.03749187e-01
 6.35108110e-04 5.27684476e-01 9.63742244e-01 3.56552562e-01
 6.07972011e-01 2.21513675e-01 5.30489698e-01 1.27072064e-01
 5.79139144e-01 6.56762326e-01 6.44682360e-01 1.36029370e-01
 5.46603119e-01 6.20591454e-01 1.24672840e-01 3.39111835e-02
 9.14120227e-01 3.35569355e-01 8.69287430e-01 9.19267055e-01
 6.46514346e-01 4.62870198e-01 4.66584743e-03 3.06689973e-01
 5.89026116e-02 1.02249738e-01 5.43989705e-01 6.07130998e-01
 2.16856830e-01 7.92134053e-01 8.21235467e-01 1.13678508e-01
 9.54179685e-01 9.17257856e-01 6.76744168e-02 6.18588261e-01
 7.14744301e-01 6.85970122e-01 8.43447804e-01 5.58404753e-01
 3.64976533e-01 4.33128079e-01 3.36450060e-02 7.74397333e-01
 3.38610945e-01 4.42806711e-01 1.60072553e-02 5.06988354e-01
 6.18804871e-01 1.557430



Задание 5.Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])


In [33]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    x = np.array([k for k, g in groupby(a)])
    num = np.array([len(list(g)) for k, g in groupby(a)])
    return x, num

In [34]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 54.6 µs




Задание 6. Пусть задан некоторый одномерный массив X . Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив X при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.

Пример: X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]


In [35]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    new_X = X.copy()
    new_X[1::2] = a
    new_X[::2] **= 3
    new_X = new_X[::-1]
    result = np.concatenate((X, new_X))
    return result[::-1]

In [36]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 90 µs, sys: 13 µs, total: 103 µs
Wall time: 108 µs
